# Generated by Django 4.0.4 on 2022-05-18 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='job_tittle',
            new_name='job_title',
        ),
    ]
